# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZM4yR-RZbg8HeZYz3gXHVefMNfUKD6Y
"""



#ATM project
#insert card
pin = input("Enter your 4 digit pin number")
SB = 100000
CA = 50000
if pin=='1234':
  print("Correct pin")
  account = input("Enter type of account")
  if account=="SB":
    print("You are choosing SB account")
    amount = int(input("Enter your amount"))
    if (amount<=50000):
      print("Transcation is processing")
      balance = (SB) - (amount)
      print("Remaining balance in your account is:",balance)
    else:
      print("Exist withdrawal limit")
  else:
    print("You are choosing Current Account")
    amount = int(input("Enter your amount"))
    if (amount<= 25000):
      print("Transcation is processing")
      balance1 = CA-amount
      print("Remaining balance in your account is:",balance1)
    else:
      print("Exist withdrawal limit")
else:
  print("Incorrect pin")